services:
  app:
    image: local/${SERVICENAME}
    restart: unless-stopped
    container_name: ${SERVICENAME}
    volumes:
      - "${VOLUMES_DIR}/images:/var/www/html/images"
    environment:
      - DOMAINNAME
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD
      - MYSQL_DATABASE=database
      - LDAP_HOST=ldap
      - LDAP_BIND_DN=cn=admin,dc=mind-hochschul-netzwerk,dc=de
      - LDAP_BIND_PASSWORD
      - SMTP_HOST
      - SMTP_SECURE
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASSWORD
      - SECRET_KEY
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.${SERVICENAME}.entrypoints=websecure
      - traefik.http.routers.${SERVICENAME}.rule=Host(`${SERVICENAME}.${DOMAINNAME}`)
    depends_on:
      - db
    networks:
      - traefik
      - ldap
      - default

  db:
    image: mariadb
    restart: unless-stopped
    container_name: ${SERVICENAME}-db
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD
    volumes:
      - "./docker/sql:/docker-entrypoint-initdb.d:ro"
      - "${VOLUMES_DIR}/mariadb:/var/lib/mysql"

  adminer:
    image: adminer
    container_name: ${SERVICENAME}-adminer
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.${SERVICENAME}-adminer.entrypoints=websecure
      - traefik.http.routers.${SERVICENAME}-adminer.rule=Host(`${SERVICENAME}-adminer.${DOMAINNAME}`)
    depends_on:
      - db
    networks:
      - traefik
      - default

networks:
  traefik:
    name: traefik
    external: true
  ldap:
    name: ldap
    external: true
